all:polygon_set_data_test.cpp connectivity_extraction_usage.cpp
	g++ -g polygon_set_data_test.cpp -o pset -lrt 
	#g++ -g connectivity_extraction_usage.cpp -o cex -lrt 
clean:
	#rm -rf ex
	#rm -rf cex
	rm -rf pset
